name: Pipeline CI - DevSecOps CUN

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  pruebas:
    name: Pruebas Unitarias
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      - name: Instalar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install flask pytest

      - name: Ejecutar pruebas unitarias
        run: |
          pytest tests/ -v -k "not test_login_page_carga"

  seguridad-sast:
    name: Análisis de Seguridad SAST
    runs-on: ubuntu-latest
    needs: pruebas

    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      - name: Instalar Semgrep
        run: pip install semgrep

      - name: Ejecutar análisis SAST
        run: |
          semgrep --config=auto --lang=python app.py --severity=WARNING

      - name: Guardar reporte de seguridad
        if: always()
        run: |
          semgrep --config=auto --lang=python app.py --json > reporte_seguridad.json || true

      - name: Subir reporte como artefacto
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reporte-seguridad
          path: reporte_seguridad.json

  dependencias:
    name: Verificar Dependencias Seguras
    runs-on: ubuntu-latest
    needs: pruebas

    steps:
      - name: Descargar código del repo
        uses: actions/checkout@v4

      - name: Instalar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar pip-audit
        run: pip install pip-audit

      - name: Auditar dependencias
        run: |
          pip install -r requirements.txt
          pip-audit
